log:
  telegram:
    chatID: "-4672893880"
    token: "7945687310:AAHA9tkUPV1ELEsVSLoDZe_Cc76wp7YdDVI"
  alerter:
    enabled: true
    prefix: "api-client"                   # 告警消息前缀，用于标识服务名
    format: html                           # 默认html格式，可选json格式
  logger:
    mode: 1                                # 0:dev 1:prod
    level: debug                           # 日志级别 "debug", "info", "warn", "error"
    appName: "api-client"
    directory: "./logs"
    formatJson: false
    errorFile: false
    sensitive: []
    rotate:
      maxSizeMB: 100
      maxBackups: 0
      maxAgeDays: 7
      compress: true
      localTime: true
press:
  open: true
  url: "ws://127.0.0.1:3102/"
  num: 2
  batch: 10
  interval: 10000   # ms
  startID: 600000
  minMoney: 100.0
  maxMoney: 10000.0


