server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  tcp:
    addr: 0.0.0.0:3101
    timeout: 1s
  websocket:
    addr: 0.0.0.0:3102
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  telegram:
    chatID: "-4672893880"
    token: "7945687310:AAHA9tkUPV1ELEsVSLoDZe_Cc76wp7YdDVI"
  alerter:
    enabled: true
    prefix: "api-server"                   # 告警消息前缀，用于标识服务名
    format: html                           # 默认html格式，可选json格式
  logger:
    mode: 1                                # 0:dev 1:prod
    level: debug                           # 日志级别 "debug", "info", "warn", "error"
    appName: "api-server"
    directory: "./logs"
    formatJson: false
    errorFile: false
    sensitive: [ "password", "token" ]
    rotate:
      maxSizeMB: 100
      maxBackups: 10
      maxAgeDays: 7
      compress: true
      localTime: true

room:
  table:
    tableNum: 1000
    chairNum: 5
  game:
    vid: 1002
    min_money: 100.0
    max_money: 10000.0
    base_money: 1.0
    auto_ready: true
    ch_limit: 600.0
    pot_limit: 800.0
    see_round: 3
    auto_see_round: 6
    fee: 0.05
    speaker_minmoney: 200.0
    speaker_card_type: 2
    high_strength_rate: 30
  robot:
    open: true
    num: 5
    table_max_count: 4
    min_play_count: 3        # 预留n个AI自己玩游戏 (废弃)
    id_begin: 100000
    min_money: 100.0
    max_money: 10000.0
    stand_min_money: 200.0
    stand_max_money: 8000.0
    reserveN: 1                # 预留N桌AI自己玩游戏
  logCache:
    open: true
