// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int32                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`           // 操作码：0=Push, 1=Request, 2=Response, 3=Ping, 4=Pong, 5=Sub, 6=Unsub, 7=Pub
	Place         int32                  `protobuf:"varint,2,opt,name=place,proto3" json:"place,omitempty"`     // 占位字段，可忽略或保留
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号（Request 对应 Response）
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`       // 错误码
	Command       int32                  `protobuf:"varint,5,opt,name=command,proto3" json:"command,omitempty"` // 命令编号 (如LoginReq=1001)
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`        // 业务数据ProtoMessage（如 LoginReq/Resp/MatchPush 的二进制）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Payload) GetPlace() int32 {
	if x != nil {
		return x.Place
	}
	return 0
}

func (x *Payload) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Payload) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Payload) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\x0fwebsocket.proto\"\x83\x01\n" +
	"\aPayload\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x12\x14\n" +
	"\x05place\x18\x02 \x01(\x05R\x05place\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x18\n" +
	"\acommand\x18\x05 \x01(\x05R\acommand\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04bodyB\x17Z\x15websocket/proto;protob\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_api_proto_goTypes = []any{
	(*Payload)(nil), // 0: websocket.proto.Payload
}
var file_proto_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
