// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yola1107/kratos/v2"
	"github.com/yola1107/kratos/v2/log"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/biz"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/conf"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/core/room"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/data"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/server"
	"github.com/yola1107/kratos/v2/ztest/api-server/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRoom *conf.Room, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	roomRoom := room.New(confRoom)
	greeterService := service.NewGreeterService(greeterUsecase, roomRoom)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	websocketServer := server.NewWebsocketServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer, websocketServer, roomRoom)
	return app, func() {
		cleanup()
	}, nil
}
