// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yola1107/kratos/v2"
	"github.com/yola1107/kratos/v2/log"
	"github.com/yola1107/kratos/v2/ztest/game/ludo/internal/biz"
	"github.com/yola1107/kratos/v2/ztest/game/ludo/internal/conf"
	"github.com/yola1107/kratos/v2/ztest/game/ludo/internal/data"
	"github.com/yola1107/kratos/v2/ztest/game/ludo/internal/server"
	"github.com/yola1107/kratos/v2/ztest/game/ludo/internal/service"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, room *conf.Room, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, client)
	if err != nil {
		return nil, nil, err
	}
	dataRepo := data.NewDataRepo(dataData, logger)
	usecase, cleanup2, err := biz.NewUsecase(dataRepo, logger, room)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService := service.NewService(usecase, logger)
	grpcServer := server.NewGRPCServer(confServer, serviceService, logger)
	httpServer := server.NewHTTPServer(confServer, serviceService, logger)
	websocketServer := server.NewWebsocketServer(confServer, serviceService, logger)
	app := newApp(logger, grpcServer, httpServer, websocketServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
