// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: conf/conf_public.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          *PublicConfig_Lang     `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicConfig) Reset() {
	*x = PublicConfig{}
	mi := &file_conf_conf_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicConfig) ProtoMessage() {}

func (x *PublicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicConfig.ProtoReflect.Descriptor instead.
func (*PublicConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_public_proto_rawDescGZIP(), []int{0}
}

func (x *PublicConfig) GetLang() *PublicConfig_Lang {
	if x != nil {
		return x.Lang
	}
	return nil
}

type PublicConfig_Lang struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicConfig_Lang) Reset() {
	*x = PublicConfig_Lang{}
	mi := &file_conf_conf_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicConfig_Lang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicConfig_Lang) ProtoMessage() {}

func (x *PublicConfig_Lang) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicConfig_Lang.ProtoReflect.Descriptor instead.
func (*PublicConfig_Lang) Descriptor() ([]byte, []int) {
	return file_conf_conf_public_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PublicConfig_Lang) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicConfig_Lang) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_conf_conf_public_proto protoreflect.FileDescriptor

const file_conf_conf_public_proto_rawDesc = "" +
	"\n" +
	"\x16conf/conf_public.proto\x12\n" +
	"kratos.api\"m\n" +
	"\fPublicConfig\x121\n" +
	"\x04lang\x18\x01 \x01(\v2\x1d.kratos.api.PublicConfig.LangR\x04lang\x1a*\n" +
	"\x04Lang\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\"Z kratos-layout/internal/conf;confb\x06proto3"

var (
	file_conf_conf_public_proto_rawDescOnce sync.Once
	file_conf_conf_public_proto_rawDescData []byte
)

func file_conf_conf_public_proto_rawDescGZIP() []byte {
	file_conf_conf_public_proto_rawDescOnce.Do(func() {
		file_conf_conf_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_public_proto_rawDesc), len(file_conf_conf_public_proto_rawDesc)))
	})
	return file_conf_conf_public_proto_rawDescData
}

var file_conf_conf_public_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conf_conf_public_proto_goTypes = []any{
	(*PublicConfig)(nil),      // 0: kratos.api.PublicConfig
	(*PublicConfig_Lang)(nil), // 1: kratos.api.PublicConfig.Lang
}
var file_conf_conf_public_proto_depIdxs = []int32{
	1, // 0: kratos.api.PublicConfig.lang:type_name -> kratos.api.PublicConfig.Lang
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_conf_conf_public_proto_init() }
func file_conf_conf_public_proto_init() {
	if File_conf_conf_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_public_proto_rawDesc), len(file_conf_conf_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_public_proto_goTypes,
		DependencyIndexes: file_conf_conf_public_proto_depIdxs,
		MessageInfos:      file_conf_conf_public_proto_msgTypes,
	}.Build()
	File_conf_conf_public_proto = out.File
	file_conf_conf_public_proto_goTypes = nil
	file_conf_conf_public_proto_depIdxs = nil
}
